credentials:
  usernames:
    marco:
      email: marco@example.com
      name: Marco
      password: SenhaForte123!Marcos
cookie:
  expiry_days: 30
  key: gerador_json_hybris_secret_key_2025
  name: hybris_json_generator_auth
preauthorized:
  emails: []
